### PR TITLE
Update LICENSE to reference JSF trademark policy

### PR DESCRIPTION
**Pull request by kborchers**

### CODE REVIEW

**Comment by kborchers** [comment]
Would someone mind merging this ASAP please? @TheLarkInn

**Comment by TheLarkInn** [comment]
Thanks for the ping @kborchers I wouldn't have seen this because I've been in Poland this week. Let me review the JS Foundation trademark policy first and can merge it!

**Comment by kborchers** [comment]
Ping :)

**Comment by kborchers** [comment]
Can someone merge this today please? If you are too busy, we can merge it ourselves. Thanks!

**Comment by kborchers** [comment]
Please merge this PR today.

**Pull request merged**
